use_frameworks!

platform :ios, '8.0'

target 'LewinVCRouter_Example' do
  pod 'LewinVCRouter', :path => '../'

  target 'LewinVCRouter_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
